import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { LoginButton } from "@/components/login-button";
import { DashBoardLink } from "@/components/dashboard-link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-gray-50">
          <header className="bg-white shadow">
            <div className="max-w-7xl mx-auto px-4  py-6">
              <div className="flex justify-between items-center">
                <Link href="/" className="text-3xl font-bold text-gray-900">
                  Eventos
                </Link>
                <DashBoardLink />
                <LoginButton />
              </div>
            </div>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
